config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :users
  resources :user_sessions
  root 'dashboards#index'
  get '/admin', to: 'admin#index'
  
  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in

end

app/models/course.rb
class Course < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic do |c|
     c.crypto_provider = Authlogic::CryptoProviders::SCrypt
  end
  after_create :activate_user
    def activate_user
      #if a user is successfully created set the active field to true
      self.active = true
      self.approved = true
      self.confirmed = true
      self.save
    end
  # def valid_password?(entered_password) 
  #   #TODO Implement password checking  
  #   if entered_password == password 
  #     return true 
  #   else
  #     return false 
  #   end   
  # end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	def index
		@course = Course.new
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #filter_parameter_logging :password, :password_confirmation # there are underscores :-|

  helper_method :current_user_session, :current_user

  private
    def current_user_session
      return @current_user_session if defined?(@current_user_session)
      @current_user_session = UserSession.find
    end

    def current_user
      return @current_user if defined?(@current_user)
      @current_user = current_user_session && current_user_session.user
    end

    helper_method :current_user_session, :current_user

    def require_user
      logger.debug "ApplicationController::require_user"
      unless current_user
        store_location
        flash[:notice] = "You must be logged in to access this page"
        redirect_to new_user_session_url
        return false
      end
    end

    def require_no_user
      logger.debug "ApplicationController::require_no_user"
      if current_user
        store_location
        flash[:notice] = "You must be logged out to access this page"
       # redirect_to home_index_path
        return false
      end
    end

    def store_location
      #session[:return_to] = request.request_uri
    end

    def redirect_back_or_default(default)
      redirect_to(session[:return_to] || default)
      session[:return_to] = nil
    end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def new
    @course = Course.new 
  end

  def create
    @course = Course.new(course_params)
    if @course.save!
      flash[:success] = "Course Created!"
      redirect_to root_path
    else
      render :new
    end
  end

  def index
    @courses = Course.all
  end  
private

def course_params
params.require(:course).permit(:name, :description, :status, :limit, :start_date)
end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def index
    check_user 
    @courses = Course.all
  end

  private
  
    def check_user
      logger.debug "DashboardsController::check_user"
      unless current_user
        redirect_to user_sessions_url
        return false
      end
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController 
 

 def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(user_session_params)
    if @user_session.save
      flash[:success] = "Welcome back!"
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    current_user_session.destroy
    flash[:success] = "Goodbye!"
    redirect_to root_path
  end

  private

  def user_session_params
    params.require(:user_session).permit(:email, :password, :remember_me)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def new
    @user = User.new
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if @user.save
      flash[:success] = "Account registered!"
      redirect_to root_path
    else
      render :new
    end
  end


  private

  def users_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<table class="table">
	<tbody>
		<tr>
			<td>Introduction to Ruby on Rails</td>
			<td>Programming</td>
		</tr>
		<tr> 
			<td colspan="2">
				<button class="btn btn-primary" data-toggle="modal" data-target="#AddCourse">
					<span class="glyphicon glyphicon-plus"></span> Add course
				</button>
			</td>
		</tr>
	</tbody>
</table>

<div class="modal" id="AddCourse" role="dialog" aria-labelledby="AddCourselabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title" id="AddCourselabel">Add Course</h4>

			</div>
			<div class="modal-body">
				<%= simple_form_for @course do |f| %>
				    <%= f.input :name %>
				    <%= f.input :status %>
				    <%= f.input :description %>
				    <%= f.input :limit %>
				    <%= f.input :start_date %>
					<br />  
					<%= f.submit 'Create' %>
				<% end %>	  
			</div>

		</div>
	</div> 
	
</div>

app/views/courses/new.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
<h1>Enter Your Course Details</h1>
<%= simple_form_for @course do |f| %>
    <%= f.input :name %>
    <%= f.input :status %>
    <%= f.input :description %>
    <%= f.input :limit %>
    <%= f.input :start_date %>
  <br />  
    <%= f.submit 'Create' %>
  <% end %>
</div>  

app/views/dashboards/index.html.erb
<div class="jumbotron">
<div class="container">
  <h1>Welcome!</h1>
  <p>This is your Dashboard.</p>
  <p>
  <% @courses.each do |course|%>
   <p><%= course.name %>
     <%= course.description %>
   <br />  
     <%= course.status %>
   </p> 
   <%end%>
    
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rorganizer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar navbar-inverse">
      <div class="container-fluid">
    
        <nav>
          <span class="navbar-brand" >
            <%= link_to "Rorganizer", root_path %> 
          </span>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <% if current_user %>
              <li><span><%= current_user.email %></span></li>
              <li><%= link_to 'Sign Out', sign_out_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'Sign In', sign_in_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
</header>
<div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>

<%= yield %>
</div>
</body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <% if object.errors.messages[:password] == ["is not valid"] || object.errors.messages[:email] == ["is not valid"] %>
    <div class="panel panel-heading panel-warning errors">
      <h5><i class="glyphicon glyphicon-exclamation-sign"></i> Incorrect email or password</h5>
    </div>
  <% else %>
    <div class="panel panel-warning errors">
      <div class="panel-heading">
        <h5><i class="glyphicon glyphicon-exclamation-sign"></i> Found errors while saving</h5>
      </div>
      <ul class="panel-body"> 
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/user_sessions/index.html.erb
<div class="jumbotron">
<div class="container">
  <h1>Welcome!</h1>
  <p>Sign up to get started.</p>
  <p>
    <%= link_to new_user_path, class: 'btn btn-primary btn-lg' do %>
      Sign Up &raquo;
    <% end %>
  </p>
</div>

app/views/user_sessions/new.html.erb
<div class="page-header"><h1>Sign In</h1></div>

<%= form_for @user_session do |f| %>
  <%= render 'shared/errors', object: @user_session %>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :remember_me %>
    <%= f.check_box :remember_me %>
  </div>

  <%= f.submit "Log in!", class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/users/new.html.erb
<div class="page-header"><h1>Register</h1></div>

<%= form_for @user do |f| %>
  <%= render 'shared/errors', object: @user %>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <%= f.submit 'Register', class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/users/user_login.html.erb
<%= form_for @user_session do |f| %>
  <% if @user_session.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user_session.errors.count, "error") %> prohibited:</h2>
    <ul>
      <% @user_session.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <%= f.label :login %><br />
  <%= f.text_field :login %><br />
  <br />
  <%= f.label :password %><br />
  <%= f.password_field :password %><br />
  <br />
  <%= f.submit "Login" %>
<% end %>